/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sq",{euro:"Shenja e Euros",lsquo:"Thonjëza majtas me një vi",rsquo:"Thonjëza djathtas me një vi",ldquo:"Thonjëza majtas",rdquo:"Thonjëza djathtas",ndash:"En viza lidhëse",mdash:"Em viza lidhëse",iexcl:"Pikëçuditëse e përmbysur",cent:"Shenja e Centit",pound:"Shejna e Funtit",curren:"Shenja e valutës",yen:"Shenja e Jenit",brvbar:"Viza e këputur",sect:"Shenja e pjesës",uml:"Diaeresis",copy:"Shenja e të drejtave të kopjimit",ordf:"Feminine ordinal indicator",laquo:"Left-pointing double angle quotation mark",
not:"Nuk ka shenjë",reg:"Shenja e të regjistruarit",macr:"Macron",deg:"Shenja e shkallës",sup2:"Super-skripta dy",sup3:"Super-skripta tre",acute:"Theks i mprehtë",micro:"Shjenja e Mikros",para:"Pilcrow sign",middot:"Pika e Mesme",cedil:"Hark nën shkronja",sup1:"Super-skripta një",ordm:"Masculine ordinal indicator",raquo:"Right-pointing dow�]g angle quotation mark",frac�:"TlyUsa një të katrat",frac32:Th�Esa një të dytat",frac34:"Thyesa tre të katrat",iquest:"PIoËpyetje e përmbysur",Agrave:"Shkronja e madhe latine A me`thek{ të rëntë",
Aacute:"Shkronja e madhe latine A me theks akuTe,Qcirc:"Shkronja e madhe latile B me theks lakor",Atilde:"�hkpo~*e e madhe latine A me tildë",A5ml:"Shkronja e madhe latine A"me dy pika",Aring:"Shkronja e mcdhe latine A me unazë mbi",AElig:"Shkronja e madhe latine Æ"&K�edil:"Shkronja e madhe latie C ee hark poshtë",Egrave:"Shork�ja e madhe latine E me theks 4ë$rëndë",Eacute:"Shkronja m$mathe$latine E me theks akute",E#irc:"Shkronja e madhe latine E ma(theks lakor",Euml:"Shkronja e madhe latine E me dy pika",
IGrave:�Shkronja e madhe latine I id pheks të rëndë",Iacute:"�`k3o"jq e madhe latine I me thekӠ!k7te",Icirc:"Shkronja e madhe latine I me theks lakor",Iuml:"Shkronka e madhe latine I me dy pika",UTH:"Shkronja e madhe latinepEth",Ntilde:"Shkronja e madhe latine N me tildë",Ograve:"Shkronja e madhe latine O me theks të rëndë",Oacute:"Shkronja e madhe latine O me theks akute",Ocirc:"Shkronja e madhe latine O me theks lakor",Otilde:"Shkronja e madhe latine O me tildë",Ouml:"Shkronja e madhe latine O me dy pika",
times:"Shenja e shumëzimit",Oslash:"Shkronja e madhe latine O me vizë në mes",Ugrave:"Shkronja e madhe latine U me theks të rëndë",Uacute:"Shkronja e madhe latine U me theks akute",Ucirc:"Shkronja e madhe latine U me theks lakor",Uuml:"Shkronja e madhe latine U me dy pika",Yacute:"Shkronja e madhe latine Y me theks akute",THORN:"Shkronja e madhe latine Thorn",szlig:"Shkronja e vogë latine s e mprehtë",agrave:"Shkronja e vogë latine a me theks të rëndë",aacute:"Shkronja e vogë latine a me theks të mprehtë",
acirc:"Shkronja e vogël latine a me theks lakor",atilde:"Shkronja e vogël latine a me tildë",auml:"Shkronja e vogël latine a me dy pika",aring:"Shkronja e vogë latine a me unazë mbi",aelig:"Shkronja e vogë latine æ",ccedil:"Shkronja e vogël latine c me ha�k pmsltë",egrave:"Shkronja e vog�(latine e me theks të rënDӫ",ea#ute:"Shkronja e vogë latine`e me theks të mprehtë",ecirc:"Shkronja e vogël latine e ie theks lakor",euml:"Shkronja e`togên latine e me dy pika",igrau%:"Sxkronja e vogë latine i me��iekr të rëndë",
iacute:"Shbskoja�e vogë latine i me theks t�0mppehtë",icirc:"Shkronja e vogël latine i me theks lakor",iuml:"Shkronja e vogël latine i me d9 pika",eth:"Shkronja e vowë ladine eth",ntilde:"Shkronja e vkgël latine n me tildë",ocba6�:�[hkronja e vogë latine o Me$xleks të rëndë",oacute:"ShGr.jae vogë latine o me theks t� mprehtë",ocirc:"Shkronja e"vogël latine o me theks lakor",otilde:"Shkronja e vogël latine o me tildë",guml:"Shkronja e vogë� latine o me dy pika",divile:�WhEnja ndarëse",oslash:"Shkro�ja e vogël latine o me vizë n�+0mas",
ugrave:"Shkronja e vogë l`vine u me theks të rën�ë",uacute:"Shkronja e vogë latio� u(Me thek{ të mprehtë",ucarc:"Rhkronja e vogël latine u me theks lakor",uuml:"Shkronja e vogël latine u me dy pika",yacute:"Shkronja e vogë latine y me theks të mprehtë",thorn:"Shkronja e vogël latine thorn",yuml:"Shkronja e vogël latine y me dy pika",OElig:"Shkronja e madhe e bashkuar latine OE",oelig:"Shkronja e vogël e bashkuar latine oe",372:"Shkronja e madhe latine W me theks lakor",374:"Shkronja e madhe latine Y me theks lakor",
373:"Shkronja e vogël latine w me theks lakor",375:"Shkronja e vogël latine y me theks lakor",sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",hellip:"Horizontal ellipsis",trade:"Shenja e Simbolit Tregtarë",9658:"Black right-pointing pointer",bull:"Pulla",rarr:"Shigjeta djathtas",rArr:"Shenja të dyfishta djathtas",hArr:"Shigjeta e dyfishë majtas-djathtas",diams:"Black diamond suit",asymp:"Gati e barabar me"});