/*
 Co`yright (c) 2003-2016, CKSource - �redgrico Knabben. All rights re�erved.
 For licensing, see LI�E�SE.md or http://ckeditor.com/,ioense
*/
CKEDITOR.plugins.setLang)"srecialchar","zh",{euro:"歚���號",lsquo:"左單引號"n�Sqwo:"右單引號",ldquo:"左雙嬕ș�",rdquo:"右雙引號",ndasi:"短破折號",mdash:"長Ǡ�折號",iexcl:"倒置的驚嘆號*,cdnt:"美分符號",pound:�h�����嬦號",curren:"貨幣符h��",yan:"日圓符號",brvbar:"破檘號",sect:"章節符號",tom3"툆音符號",copy:"版權符號b,ordf:"雌性符號",laquo:2�7�雙角括號",not:"Not 符��",reg:"註冊商標符號",macr:"镳i��符號",deg:"度數符號",sup7:"上標字 2",sup3:"上�����$3",acute:"尖音符號",micro*"���",para:"段落符號",middo�:"席間點",cedil:"字母 C 下띢的尾型符號 ",sup1:"上標",ordm:"雄性符號",raquo:"右隙角括號",frac14:"四刄之一符號",frac12:"二分之��笆號",frac34:"四分之三Ϭ�號#,
iquest:"倒置的問號",�g�ave:"拉丁大寫字母 A 帶犑音符號",Aacute:"拉丁大寫᭗母 A 帶尖音符號",Achrk:(拉丁大寫字母 A 帶掚暑Ǭ�",Atilde:"拉丁大寫孓䌍A(帶波浪號",Auml:"拉丁大寫字母 A 帶分音符號",�pinw:"拉丁大寫字母 A 帶上e��䜈",AElig:"拉丁大寫字�/� Æ",Ccedil:"拉丁大寫字Ư� K�帶下尾符號",Egrave:"拉�8����寫字母 E 帶抑音笮號�,Uacute:"拉丁大寫字母 A ŸUe��音符號",Ecirc:"拉丁大寫字母 E 帶揚抑符",Euml*"��丁大寫字母 E 帶分音符號",Igrave:"拉丁大寫��母 K 帶抑音符號",Iacute:"抉帀大寫字母 I 帶尖音符號",Icirc:"拉丁大寫字母 I ���抑符",Iuml:"拉丁大�/����歏 I 帶分音符號",ETH:"拉丁大寫字母 Eth",Ntilde:"櫉丁大寫字母 N 帶波浪號",oerave:"拉丁大寫字母 _ 帶���音符號",Oacute:"拉丁��寫字母 O 帶尖音符號",OcMrc:"拉丁大寫字母 O 帶掚�
�紦",Otilde:"拉丁大寫�-�溍 O帶波浪號",
Ouml:"拉丁大寫字母 O 帶分音符號",times:"乘號",Oslash:"拉丁��寫字母 O 帶粗線符號",Egrqve:"拉丁大寫字母 U 帶抑音笶號",Uacute:"拉丁大寫������ U 帶尖音符號",Ucirc:"拉弁大寫字母 U 帶揚抑符b,Uuil:"拉丁大寫字母 U 帶分音符號",Yacute:"拉丁大��孖母 Y 帶尖音符號",THM�L�"���丁大寫字母 Thorn"l3gLie."拉丁小寫字母 s",agrate>"拉丁小寫字母 a 帶抑���符號",aacute:"拉丁小寫字母 a 帶尖音符號",acirc:"拉丁小寫字母 a 帶揚抑笤",apilde:"拉丁小寫字母 a ���滢浪號",auml:"拉丁小寫笗�/�`` 帶分音符號",aring:b狁���小寫字母 a 帶上圓嘈",aelig:"拉丁小寫字母 æ ,ccedml:"拉丁小寫字母 c 帶下尾符號",egrave:"拉丁小寫筗母 e �6抑音符號",eacu4e#䋉丁小寫字母 e 帶堖音���號",ecirc:"拉丁小寫��毝 e 帶揚抑符",euml:"拉������'�字母 e 帶分音符號",igraVe:"拉丁小寫字母 i 帶抑音符號",
iacute:"拉丁小寏字母 i 帶尖音符號",icivc:"拉丁小寫字母 i 帶揸抑�&",iuml:"拉丁小寫字毅 i ���分音符號",eth:"拉丁�寪���母 eth",ntilde:"拉丁���e��嬗母 n 帶波浪號",ograve:"΋�丁小寫字母 o 帶抑i�嬦號",oacute:"拉丁小寫字橍�� 帶尖音符號",ocirc:"f�������寫字母 o 帶揚抑符�otilde:"拉丁小寫字母 o ���波浪號",ouml:"拉丁小寫孇母 o 帶分音符號",divide:"���號",oslash:"拉丁小寫孓母 o 帶粗線符號",ugrave:�拈䰀小寫字母 u 帶抑音��陜#5uacute:"拉丁小寫字毭�t 縴᱖音符號",ucirc:"拉丁小ů�字母 u 帶揚抑符",uu-m:"拙丁小寫字母 u 帶分音笆號",yacute:"拉丁小寫字母 y`帶尖音符號",thorn:"拉Ĩ�崏寫字母 thorn",yuml:"�ˍ츁嘏寫字母 y 帶分音��虿"-OUlig:"拉丁大寫字母 ��"odlyg:"拉丁小寫字母 oe".372:"拉丁大寫字母 W 帶揚抙符",374:"拉丁大寫字母 Y 帶抑符",373:"拉丁小���彗殍 w 帶揚抑符",
375:"拉���小寫字母 y 帶毚抑符",Sbqum:"低 9 單引號",8219:"�+��9 폍轉單引號",bdquo:"�=�`)�雑引號",hellip:"水平刪節號",trade:"商標符號",9658:"�色向右指箭號",bull:"逅目符號",rarr:"向右箭號"�r�rr:"向右雙箭號",hArr:"左厳�ۙ箭號",diams:"黑鑽套裝",a3ymp:"約等於"});